/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  tag?: string;
  excerpt?: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ForCompanies = {
  _id: string;
  _type: "forCompanies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading?: string;
  lede?: string;
  columns?: Array<{
    title?: string;
    bullets?: Array<string>;
    _type: "column";
    _key: string;
  }>;
  ctaLabel?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  meta?: string;
  categories?: Array<string>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  summary?: string;
  stack?: Array<string>;
  githubUrl?: string;
  authors?: string;
  roleNote?: string;
  sections?: Array<{
    heading?: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }
      | {
          code?: string;
          language?: string;
          _type: "codeBlock";
          _key: string;
        }
    >;
    _type: "projectSection";
    _key: string;
  }>;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  order?: number;
  role?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  skills?: Array<string>;
  learning?: Array<string>;
  linkedin?: string;
  github?: string;
  email?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
  >;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroCaption?: string;
  eyebrow?: string;
  headline?: string;
  subline?: string;
  ctaPrimary?: {
    label?: string;
    href?: string;
  };
  ctaSecondary?: {
    label?: string;
    href?: string;
  };
  introEyebrow?: string;
  introHeading?: string;
  introBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
  >;
  membersHeading?: string;
  membersLede?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groupName?: string;
  responsePromise?: string;
  nav?: Array<{
    label?: string;
    href?: string;
    _type: "navItem";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ForCompanies
  | Project
  | Member
  | About
  | Home
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{ groupName, responsePromise, nav[]{label, href} }
export type SITE_SETTINGS_QUERY_RESULT = {
  groupName: string | null;
  responsePromise: string | null;
  nav: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "home": *[_type == "home" && _id == "home"][0]{    heroImage{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },    heroCaption,    eyebrow,    headline,    subline,    ctaPrimary,    ctaSecondary,    introEyebrow,    introHeading,    introBody,    membersHeading,    membersLede  },  "members": *[_type == "member"] | order(order asc){    _id,    name,    order,    role,    portrait{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },    bio,    skills,    learning,    linkedin,    github,    email  },  "forCompanies": *[_type == "forCompanies" && _id == "forCompanies"][0]{    eyebrow, heading, lede, columns[]{title, bullets}, ctaLabel  }}
export type HOME_QUERY_RESULT = {
  home: {
    heroImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
    heroCaption: string | null;
    eyebrow: string | null;
    headline: string | null;
    subline: string | null;
    ctaPrimary: {
      label?: string;
      href?: string;
    } | null;
    ctaSecondary: {
      label?: string;
      href?: string;
    } | null;
    introEyebrow: string | null;
    introHeading: string | null;
    introBody: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          code?: string;
          language?: string;
          _type: "codeBlock";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }
    > | null;
    membersHeading: string | null;
    membersLede: string | null;
  } | null;
  members: Array<{
    _id: string;
    name: string | null;
    order: number | null;
    role: string | null;
    portrait: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
    bio: string | null;
    skills: Array<string> | null;
    learning: Array<string> | null;
    linkedin: string | null;
    github: string | null;
    email: string | null;
  }>;
  forCompanies: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    columns: Array<{
      title: string | null;
      bullets: Array<string> | null;
    }> | null;
    ctaLabel: string | null;
  } | null;
};

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about" && _id == "about"][0]{ eyebrow, heading, body }
export type ABOUT_QUERY_RESULT = {
  eyebrow: string | null;
  heading: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(order asc){    _id, title, slug, order, meta, categories, stack, githubUrl, authors,    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },    summary  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  order: number | null;
  meta: string | null;
  categories: Array<string> | null;
  stack: Array<string> | null;
  githubUrl: string | null;
  authors: string | null;
  cover: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
  summary: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id, title, slug, meta, categories, stack, githubUrl, authors, roleNote,    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },    summary,    sections[]{heading, body}  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  meta: string | null;
  categories: Array<string> | null;
  stack: Array<string> | null;
  githubUrl: string | null;
  authors: string | null;
  roleNote: string | null;
  cover: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
  summary: string | null;
  sections: Array<{
    heading: string | null;
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          code?: string;
          language?: string;
          _type: "codeBlock";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }
    > | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id, title, slug, publishedAt, tag, excerpt  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  tag: string | null;
  excerpt: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id, title, slug, publishedAt, tag, excerpt, body,    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  tag: string | null;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  cover: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{ groupName, responsePromise, nav[]{label, href} }': SITE_SETTINGS_QUERY_RESULT;
    '{\n  "home": *[_type == "home" && _id == "home"][0]{\n    heroImage{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },\n    heroCaption,\n    eyebrow,\n    headline,\n    subline,\n    ctaPrimary,\n    ctaSecondary,\n    introEyebrow,\n    introHeading,\n    introBody,\n    membersHeading,\n    membersLede\n  },\n  "members": *[_type == "member"] | order(order asc){\n    _id,\n    name,\n    order,\n    role,\n    portrait{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },\n    bio,\n    skills,\n    learning,\n    linkedin,\n    github,\n    email\n  },\n  "forCompanies": *[_type == "forCompanies" && _id == "forCompanies"][0]{\n    eyebrow, heading, lede, columns[]{title, bullets}, ctaLabel\n  }\n}': HOME_QUERY_RESULT;
    '*[_type == "about" && _id == "about"][0]{ eyebrow, heading, body }': ABOUT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)] | order(order asc){\n    _id, title, slug, order, meta, categories, stack, githubUrl, authors,\n    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },\n    summary\n  }': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n    _id, title, slug, meta, categories, stack, githubUrl, authors, roleNote,\n    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },\n    summary,\n    sections[]{heading, body}\n  }': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)].slug.current': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id, title, slug, publishedAt, tag, excerpt\n  }': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n    _id, title, slug, publishedAt, tag, excerpt, body,\n    cover{ asset, hotspot, alt, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio }\n  }': POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
  }
}
