/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GalleryImage = {
  _type: "galleryImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  orientation?: "horizontal" | "vertical";
};

export type TechnicalSkill = {
  _type: "technicalSkill";
  title?: string;
  description?: string;
  tags?: Array<{
    name?: string;
    icon?: string;
    _type: "technicalSkillTag";
    _key: string;
  }>;
  images?: Array<
    {
      _key: string;
    } & RatioImage
  >;
};

export type StudyInstitution = {
  _type: "studyInstitution";
  name?: string;
  description?: string;
};

export type WorkExperience = {
  _type: "workExperience";
  company?: string;
  timeframe?: string;
  role?: string;
  achievements?: Array<string>;
  images?: Array<
    {
      _key: string;
    } & RatioImage
  >;
};

export type RatioImage = {
  _type: "ratioImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  width?: number;
  height?: number;
};

export type TeamMember = {
  _type: "teamMember";
  name?: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkedIn?: string;
};

export type SocialLink = {
  _type: "socialLink";
  name?: string;
  icon?: string;
  link?: string;
  essential?: boolean;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: {
    firstName?: string;
    lastName?: string;
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    email?: string;
    location?: string;
    languages?: Array<string>;
    locale?: string;
  };
  social?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  newsletter?: {
    display?: boolean;
    title?: string;
    description?: string;
  };
  home?: {
    headline?: string;
    subline?: string;
    featuredDisplay?: boolean;
    featuredTitle?: string;
    featuredHref?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  about?: {
    title?: string;
    description?: string;
    tocDisplay?: boolean;
    tocSubItems?: boolean;
    avatarDisplay?: boolean;
    calendarDisplay?: boolean;
    calendarLink?: string;
    intro?: {
      display?: boolean;
      title?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
    };
    work?: {
      display?: boolean;
      title?: string;
      experiences?: Array<
        {
          _key: string;
        } & WorkExperience
      >;
    };
    studies?: {
      display?: boolean;
      title?: string;
      institutions?: Array<
        {
          _key: string;
        } & StudyInstitution
      >;
    };
    technical?: {
      display?: boolean;
      title?: string;
      skills?: Array<
        {
          _key: string;
        } & TechnicalSkill
      >;
    };
  };
  blog?: {
    title?: string;
    description?: string;
  };
  work?: {
    title?: string;
    description?: string;
  };
  gallery?: {
    title?: string;
    description?: string;
    images?: Array<
      {
        _key: string;
      } & GalleryImage
    >;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GalleryImage
  | TechnicalSkill
  | StudyInstitution
  | WorkExperience
  | RatioImage
  | TeamMember
  | SocialLink
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Post
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: {
    firstName?: string;
    lastName?: string;
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    email?: string;
    location?: string;
    languages?: Array<string>;
    locale?: string;
  };
  social?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  newsletter?: {
    display?: boolean;
    title?: string;
    description?: string;
  };
  home?: {
    headline?: string;
    subline?: string;
    featuredDisplay?: boolean;
    featuredTitle?: string;
    featuredHref?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  about?: {
    title?: string;
    description?: string;
    tocDisplay?: boolean;
    tocSubItems?: boolean;
    avatarDisplay?: boolean;
    calendarDisplay?: boolean;
    calendarLink?: string;
    intro?: {
      display?: boolean;
      title?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
    };
    work?: {
      display?: boolean;
      title?: string;
      experiences?: Array<
        {
          _key: string;
        } & WorkExperience
      >;
    };
    studies?: {
      display?: boolean;
      title?: string;
      institutions?: Array<
        {
          _key: string;
        } & StudyInstitution
      >;
    };
    technical?: {
      display?: boolean;
      title?: string;
      skills?: Array<
        {
          _key: string;
        } & TechnicalSkill
      >;
    };
  };
  blog?: {
    title?: string;
    description?: string;
  };
  work?: {
    title?: string;
    description?: string;
  };
  gallery?: {
    title?: string;
    description?: string;
    images?: Array<
      {
        _key: string;
      } & GalleryImage
    >;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc)
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(publishedAt desc)
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  summary?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tag?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMember
  >;
  link?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        code?: string;
        language?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc)': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]': POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)] | order(publishedAt desc)': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)].slug.current': PROJECT_SLUGS_QUERY_RESULT;
  }
}
